### PR TITLE
#41: if clashing with query params or command params, propTypes keys are not passed to mapProps (closes #41)

### LINKED ISSUE #41: if clashing with query params or command params, propTypes keys are not passed to mapProps
## description
see #34 

also, params should be passed to the default getLocals

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by francescogior**
Closes #41

## Test Plan

tested on internal project

> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -107,7 +107,7 @@ const decorator = ({ declareQueries, declareCommands, declareConnect }) => (Comp
   const getLocals = mapProps || pick([
     ...(queries || []),
     ...(commands || []),
-    ...Object.keys({ ...(connect || {}), ...(local || {}) })
+    ...Object.keys({ ...(connect || {}), ...(local || {}), ...__props || {} })
```
Comment (giogonzo) [inline src/index.js]: this should be `...(__props || {})`

**Review by giogonzo — COMMENTED** [review]
Looks 👍 except for comment

**Review by giogonzo — APPROVED** [review]
