### PR TITLE
#69: container should not connect to every query/command input param (closes #69)

### LINKED ISSUE #69: container should not connect to every query/command input param
## description
At this moment, `react-container` is trying to connect to every query/command's input param, even those that are not coming from `state`.
This was not a problem since the refactoring of `buildo/state`, where we're checking that every global variable we connect to is actually declared in the `AppState`.
For this reason, we have been forced to add fake variables to the `AppState`, just to make `buildo/state` happy (e.g. https://github.com/buildo/gdsm/pull/586/files#diff-7f68bc23c5c95c78faf131f41d102221R13)

## how to reproduce
- Remove fake variables from the `AppState` in GDSM or AlinityPro and `npm start`

## specs
`react-container` should know the `AppState` and connect only to the input params that are declared in state.

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by veej**
Closes #69

### tests performed
Tested on GDSM/web:
- install local `react-container` and `state` from: https://github.com/buildo/state/pull/38
- remove all the unwanted keys from `state.js` (note: in gdsm/web, `searchId`, `selectFareId` and `reservationId` are marked as unneeded, but they're actually part of the state, so we should keep them with type `t.maybe(t.String)`)
- change the last line in `state.js` file to `export const { run, connect, appState } = init(AppState)`
- change `container.js` importing `{ appState } from 'state'` and passing it to the `containerFactory`

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -68,11 +70,11 @@ const decorator = ({ declareQueries, declareCommands, declareConnect }) => (Comp
   const queriesInputTypes = queries && Object.keys(declaredQueries.InputType) || [];
   const declaredCommands = commands && declareCommands(commands);
   const commandsInputTypes = commands && Object.keys(declaredCommands.InputType) || [];
-  const declaredConnect = (connect || local || queries || commands) && declareConnect([
+  const declaredConnect = (connect || local || queries || commands) && declareConnect(intersection([
     ...difference(queriesInputTypes, Object.keys(local || {})),
     ...difference(commandsInputTypes, Object.keys(local || {})),
     ...(connect || [])
-  ].concat(local ? ['___local'] : []));
+  ].concat(local ? ['___local'] : []), Object.keys(appState.meta.props)));
```
Comment (giogonzo) [inline src/index.js]: I think we should do this `intersection` only on `queriesInputTypes` and `commandsInputTypes`, otherwise a user could write, say, `connect: ['nonExistingKey']` and wouldn't get any warning

**Review by giogonzo — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (veej) [reply src/index.js]: whooops... of course you're right!

**Review by giogonzo — APPROVED** [review]
Looks 👍
